In [1]:
import pandas as pd
import numpy as np
from sklearn import  datasets

In [2]:
iris=datasets.load_iris()

In [3]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [4]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print(iris.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [6]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
data=pd.DataFrame({
    'Sepal Length':iris.data[:,0],
    'Sepal width':iris.data[:,1],
    'Petal length':iris.data[:,2],
    'Petal width':iris.data[:,3],
    'species':iris.target
})
data.head()

Sepal Length  Sepal width  Petal length  Petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [8]:
from sklearn.model_selection import train_test_split


In [9]:
X=data[['Sepal Length', 'Sepal width', 'Petal length', 'Petal width']]
y=data['species']


In [10]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.35)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
clf=RandomForestClassifier(n_estimators=100)

In [13]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [14]:
y_pred=clf.predict(X_test)

In [15]:
from sklearn import metrics

In [16]:
print("Accuracy :", metrics.accuracy_score(y_test, y_pred))

Accuracy : 0.9622641509433962


In [18]:
clf.predict([[3,5,4,2]])

array([1])

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns